### ISSUE TITLE
Problems using a forked branch of this project

### ISSUE THREAD

**Issue by benilovj** [rack/rack-contrib#121]
I've created [a fork](https://github.com/1Pass/rack-contrib) of this project, in order to use [a modified branch](https://github.com/1Pass/rack-contrib/tree/jsonp-with-headers).

In my Rails app, I've set the `Gemfile` to point to the branch in the fork, as I would normally do it for forked gems:

``` ruby
gem 'rack-contrib', github: '1Pass/rack-contrib', branch: 'jsonp-with-headers'
```

Due to `git-version-bump`, I'm having issues deploying this code to Heroku; the push is rejected with the following error message:

```
remote:        Fetching gem metadata from https://rubygems.org/..............
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Fetching git://github.com/1Pass/rack-contrib.git
remote:        Could not find rack-contrib-1.4.0.2.ga7a545a in any of the sources
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/..............
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Fetching git://github.com/1Pass/rack-contrib.git
remote:        Could not find rack-contrib-1.4.0.2.ga7a545a in any of the sources
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app
```

What am I doing wrong?

**Comment by maccman** [comment]
Having the same issue.

**Comment by seanhandley** [comment]
And me - any help appreciated. I can bundle locally but not on our CI server.

**Comment by lucienLopez** [comment]
The issue is coming from [rack-contrib.gemspec](https://github.com/pabse/rack-contrib/blob/master/rack-contrib.gemspec#L12):

```ruby
s.version = GVB.version rescue "0.0.0.1.ENOGVB"
```

An ugly fix would be to simply get rid of git-version-bump and simply use `s.version = "version"`

**Comment by mpalmer** [comment]
OK, after a bit of fiddling around, I've determined this is down to bundler trying to resolve everything in one big hit, rather than installing a gem's dependencies before trying to install the gem itself.  The current `master` should be free of this problem, as long as you don't have `git-version-bump` installed while you're running `bundle install` in development.  You'll get a bogus-looking version number (`0.0.0.1.ENOGVB`) in your Gemfile.lock, but that should be fine because your meaningful version identifier is the git commit hash anyway.
