### ISSUE TITLE
Rack::AcceptFormat has some non-deterministic behaviour

### ISSUE THREAD

**Issue by lupine** [rack/rack-contrib#4]
Context: I'm developing a Sinatra application that uses Rack::AcceptFormat to decide which handlers to execute (and so what gets sent back to the user) for an application that processes both YAML and HTML .

On my development/test machine (Ubuntu Hardy), when a request comes through which accepts text/html, the appended extension is .html

On my staging machine (Debian Lenny), the appended extension is instead .htm

The issue is here:
39        extension =  Rack::Mime::MIME_TYPES.invert[accept] || @ext

MIME_TYPES has multiple keys with values of 'text/html':
[[".html", "text/html"], [".htm", "text/html"]]

When it's inverted, it seems to be pot luck as to which key ends up on top.

The situation is potentially even worse for text/plain - there are four possible extensions: 
[[".log", "text/plain"],  [".text", "text/plain"],  [".conf", "text/plain"],  [".txt", "text/plain"]]

As to how to fix - I guess the simplest behaviour would be to use a subset of Rack::Mime::MIME_TYPES that avoids conflicts. I don't have a patch, because I don't really like the solution - I just can't think of anything else that doesn't change the way this middleware works. Anyone have any other ideas?

**Comment by mpalmer** [comment]
I think the solution to this problem is to deprecate the `Rack::AcceptFormat` middleware.  The way it chooses the MIME type to use is terribad all on its own, and then when you add in this issue (of multiple extensions for one MIME type), things go from bad to worse.

I'll put together a PR after the 1.3 release with a deprecation framework, and `Rack::AcceptFormat` can be its first use-case.

**Comment by mpalmer** [comment]
#115 is alive.  Closing this issue in favour of the PR.
